backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: /images/uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: collections/_posts/
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{slug}}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}